backend:
  name: github
  repo: matteopaul/gridsome-netlify
  branch: master

media_folder: "./static/uploads"
public_folder: "uploads"

collections:
  - name: "PageStructure"
    label: "PageStructure"
    folder: "pages"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
